# Read the CloudCannon documentation for more information on how to use this file:
# https://cloudcannon.com/documentation/articles/setting-global-configuration/?ssg=Hugo

# Collections are related sets of content files, typically grouped by folder.
# Here you can define your collections, as well as any
# CloudCannon configuration specific to those collections.
collections_config:
  pages:
    output: true
    parse_branch_index: true
    path: content
    base_url: /
    icon: feed
    schemas:
      default:
        path: schemas/page.md
    add_options:
      - name: Add Site Page
        editor: content
        base_path: /
        schema: default
    _enabled_editors:
      - visual
      - content

  Theme_Palette:
    output: false
    path: data/theme.yml
    disable_add: true
    disable_add_folder: true
    icon: color_lens

      
      
  docs:
    path: content/docs
    base_url: /docs
    icon: file
    disable_add_folder: true
    schemas:
      default:
        path: schemas/docs.md
    add_options:
      - name: Read the docs
        icon: local_library
        href: https://docs.cloudcannon.com
      - name: Add Document
        editor: content
        base_path: /
        schema: default
    _enabled_editors:
      - content
      - visual
    filter:
      exclude:
        - _index.md
    output: true
  data:
    output: false
    path: data
    disable_add: true
    disable_add_folder: true
    _inputs:
      small_icon:
        type: image
        comment: Dimensions - 16px x 16px
      large_icon:
        type: image
        comment: Dimensions - 32px x 32px
      apple_touch_icon:
        type: image
        comment: Dimensions - 57px x 57px
      shortcut_icon:
        type: image
        comment: Bookmark icon
      light:
        type: object
        label: Light theme color palette
      dark:
        type: object
        label: Dark theme color palette
      typography:
        type: object
        label: Text
        comment: Text color palette
      button_colors:
        type: object
        label: Buttons
        comment: Button color palette
      background_colors:
        type: object
        label: BG
        comment: Background color palette
      code_block_colors:
        type: object
        label: Code Blocks
        comment: Code block color palette
      border_colors:
        type: object
        label: Borders
        comment: Border color palette
      focus_colors:
        type: object
        label: Focus
        comment: Focus color palette
      shortcode_colors:
        type: object
        label: Shortcode
        comment: Shortcode color palette
      scrollbar_colors:
        type: object
        label: Scrollbars
        comment: Scrollbar color palette
      pagefind_colors:
        type: object
        label: Pagefind
        comment: Pagefind color palette
      text: 
        type: color
        label: Primary text
        comment: "main text color. defaults: light - #000, dark - #DBDBDB"
      flip-text:
        type: color
        comment: "text color for dark backgrounds - e.g. banner. defaults: light - #fff, dark - #DBDBDB"
      highlight: 
        type: color
        label: Highlighted text
        comment: "text color for highlighted text. defaults: light - #de935f, dark - #de935f"
      body-bg-color: 
        type: color
        comment: "main body background color. defaults: light - #fff, dark - #121516"
      code-element: 
        type: color
        label: HTML element tags
        comment: "text color for codeblock html element tags. defaults: light - #b294bb, dark - #b294bb"
      code-attribute:
        type: color
        label: HTML attributes
        comment: "text color for codeblock html attributes. defaults: light - #8abeb7, dark - #8abeb7"
      code-bool:
        type: color
        label: Boolean values
        comment: "text color for codeblock boolean values. defaults: light - #ee6868, dark - #ee6868"
      code-params:
        type: color
        label: Function/HTML parameters
        comment: "text color for codeblock function/html parameters. defaults: light - #de935f, dark - #de935f"
      code-values: 
        type: color
        label: Key values
        comment: "text color for codeblock key values. defaults: light - #b5bd68, dark - #b5bd68"
      background-body: 
        type: color
        comment: "main body background color. defaults: light - #fff, dark - #121516"
      background: 
        type: color
        comment: "background color for main content area. defaults: light - #efefef, dark - #1d1f21"
      background-alt: 
        type: color
        comment: "background color for alternate content area. defaults: light - #f7f7f7, dark - #080808"
      selection: 
        type: color
        comment: "selected text background color. defaults: light - #9e9e9e, dark - #616161"
      text-main:
        type: color
        comment: "main text color. defaults: light - #363636, dark - #DBDBDB"
      text-bright: 
        type: color
        comment: "text color for bright text. defaults: light - #000, dark - #fff"
      text-muted: 
        type: color
        comment: "text color for muted text. defaults: light - #70777f, dark - #c8c8c8"
      links: 
        type: color
        comment: "text color for links. defaults: light - #0076d1, dark - #de935f"
      focus: 
        type: color
        comment: "focus color for links. defaults: light - #0096bfab, dark - #ff4d4d"
      border:
        type: color
        comment: "border color for elements. defaults: light - #dbdbdb, dark - #ffffff"
      code: 
        type: color
        label: Codeblock text color
        comment: "text color for codeblock text. defaults: light - #000, dark - #fff"
      button-base: 
        type: color
        comment: "background color for buttons. defaults: light - #d0cfcf, dark - #2b2b2b"
      button-hover: 
        type: color
        comment: "background color for buttons on hover. defaults: light - #9b9b9b, dark - #606060"
      scrollbar-thumb: 
        type: color
        comment: "scrollbar thumb color. defaults: light - #aaaaaa, dark - #555555"
      scrollbar-thumb-hover:
        type: color
        comment: "scrollbar thumb color on hover. defaults: light - #9b9b9b, dark - #606060"
      form-placeholder: 
        type: color
        comment: "placeholder text color for form inputs. defaults: light - #949494, dark - #e0e0e0"
      form-text:
        type: color
        comment: "text color for form inputs. defaults: light - #1d1d1d, dark - #f0f0f0"
      variable:
        type: color
        comment: "text color for codeblock variable names. defaults: light - #39a33c, dark - #c85f5f"
      diffcode-added: 
        type: color
        options:
          format: hex
          alpha: true
        comment: "background color for added lines in diffcode shortcode. defaults: light - #003506, dark - #003506"
      diffcode-removed: 
        type: color
        options:
          format: hex
          alpha: true
        comment: "background color for removed lines in diffcode shortcode. defaults: light - #350000, dark - #350000"
      pagefind-ui-primary:
        type: color
        comment: "primary color for pagefind ui. defaults: light - #000, dark - #D8D8D8"
      pagefind-ui-secondary:
        type: color
        comment: "secondary color for pagefind ui. defaults: light - #000, dark - #D8D8D8"
      pagefind-ui-background:
        type: color
        comment: "background color for pagefind ui. defaults: light - #efefef, dark - #1d1f21"
      pagefind-ui-border:
        type: color
        comment: "border color for pagefind ui. defaults: light - #efefef, dark - #D8D8D8"
      pagefind-ui-tag:
        type: color
        comment: "tag color for pagefind ui. defaults: light - #efefef, dark - #1d1f21"
      html:
        type: html
      id:
        type: text
      show_until:
        type: date
        comment: Date to stop showing the banner

# Control which collections are displayed in the CloudCannon site navigation,
# and how those collections are grouped.
collection_groups:
  - heading: Base Pages
    collections:
      - pages
  - heading: Docs
    collections:
      - docs
  - heading: Site Settings
    collections:
      - data
      - Theme_Palette

# Structures


_structures:
  product_logo_structure:
    values:
      - label: Image
        icon: add_photo_alternate
        description: Add as image
        value: 
          logo_image:
          logo_image_dark:
      - label: Text
        icon: border_color
        description: Add as text
        value: 
          logo_heading: 
  footer_link_structure:
    values:
      - label: Add Image Link
        icon: add_photo_alternate
        value: 
          url_path:
          image_path:
          image_alt_text:
      - label: Add Text Link
        icon: add_link
        value: 
          url_path:
          link_title:
  nav_link_structure:
    values:
      - label: Link with Icon
        icon: add_photo_alternate
        value:
          link_title:
          link_url:
          link_label:
          link_icon_path:
      - label: Text Link
        icon: add_link
        value: 
          link_label:
          link_url:
        preview:
          text: Site Link
          icon: add_link


  
_inputs:
  title: 
    type: text
    label: Page Title
  nav_title:
    type: text
    label: Sidebar Nav Title
    comment: The name of the page shown in the sidebar navigation
  nav_section:
    type: text
    label: Parent Section
    comment: The name of the section the page is nested under in the sidebar navigation
  weight:
    type: number
    comment: The order of the page in the sidebar group
  project_name:
    type: text
  default_og_image:
    type: image
    comment: The default image for social media sharing
  logo: 
    type: object
    label: Site Logo
    comment: Choose between image or text based logos
    options:
      structures: _structures.product_logo_structure
  footer_links:
    type: array
    comment: choose between image or text based links
    options:
      structures: _structures.footer_link_structure
  logo_image:
    type: image
    comment: Default Display
  logo_image_dark:
    type: image
    comment: Displays when dark mode is enabled
  logo_text:
    type: text
  side_nav_title:
    type: text
    label: Sidebar Nav Title
  favicon:
    type: object
  nav_links:
    type: array
    label: Navigation Links
    options:
      structures: _structures.nav_link_structure
  link_title:
    type: text
    comment: Name used for alt text
  link_url:
    type: url 
    comment: 'if external link, include https://'
  link_label:
    type: text
    comment: Text displayed on the link
  link_icon_path:
    type: image
    comment: '*prefers svgs for dark mode'
  url_path:
    type: text
    comment: 'if external link, include https://'
  


  

# Snippets

_snippets:
  diffcode:
    template: hugo_paired_shortcode_named_args
    inline: false
    definitions:
      shortcode_name: diffcode
      content_key: inner_code
      named_args: 
    preview:
      text: Diffcode
      subtext: Difference formatter
      icon: difference
    picker_preview:
      text: Diffcode
      subtext: Difference formatter
      icon: difference
    _inputs:
      inner_code:
        type: code
  tree:
    template: hugo_paired_shortcode_positional_args
    inline: false
    definitions:
      shortcode_name: tree
      content_key: inner_code
    preview:
      text: Tree
      subtext: Tree directory formatter
      icon: account_tree
    picker_preview:
      text: Tree
      subtext: Tree directory formatter
      icon: account_tree
    _inputs:
      inner_code:
        type: code





# Set this to true to disable auto-detection of collections.
collections_config_override: false

# Control which data sets are available to populate select and multiselect inputs.
data_config:

# Base path to your source files, relative to the root folder of your repository.
source:

# The locations of various types of files within your site.
# Each path is relative to your site's source folder.
paths:
  data: data
  collections: content
  includes: layouts
  layouts: layouts
  static: static
  uploads: static/uploads

# Lets you control the look and behaviour of the Source Editor.
source_editor:

# Timezone of your site in IANA format. This is used by date and datetime inputs
# within the CloudCannon Data Editor.
timezone: Etc/UTC
