baseURL: /
languageCode: en-us
title: Cossidae Template
summaryLength: 30
disableKinds:
  - taxonomyTerm
markup:
  highlight:
    noClasses: false
  # ensures html inside markdown is allowed to render
  goldmark:
    renderer:
      unsafe: true
module:
  hugoVersion:
    extended: true
    min: 0.100.0

  mounts:
    - source: static
      target: static
    - source: layouts
      target: layouts
    - source: assets
      target: assets
